name: Build

on: [push]


jobs:
  linux:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      
    - name: get-cmake
      uses: lukka/get-cmake@v2.3
      
    #- name: Install Qt Multimedia deps
    #  run: sudo apt-get update && sudo apt-get install libasound2-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.5.3
      with:
        modules: qtMultimedia
      
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_C_COMPILER="/usr/bin/gcc" -DCMAKE_PREFIX_PATH="/home/runner/work/JustKeyboard/Qt 5.12.7" ..
  
    - name: Build
      run: cmake --build build --target all -- -j 4
    
